---
general:
  host: "localhost"
  port: 9999
  frame_source:
    type: "dummybody"
    parameters:
      nhumans: 10
      stopat: 1000
      device: 3
video_encoder:
  4: #object-human
    type: "null"
