---
general:
  host: "localhost"
  port: 9999
  log_level: "debug"
  frame_source:
    type: "oakd_xlink_full"
    parameters:
      ip: "192.168.10.43"
      deviceid: 1
      stream_color: True
      stream_depth: False
      stream_bodies: True
      rgb_resolution: 1080
      rgb_preview_size_y: 960
      rgb_preview_size_x: 1632 
      rgb_fps: 7
      depth_resolution: 720
      depth_preview_size_y: 320
      depth_preview_size_x: 544
      depth_fps: 7
      depth_spatial_filter: True
      depth_spatial_hole_filling_radius: 2
      depth_spatial_filter_num_it: 1
      depth_decimation_factor: 1
      streaming_color_format: "COLOR_BGRA32"
      streaming_color_resolution: "COLOR_RESOLUTION_720P"
      streaming_depth_mode: "STEREO_DISPARITY"
      streaming_depth_resolution: "STEREO_RESOLUTION_480P"
      streaming_rate: "10"
      model_person_detection: "@{REL}/models/person-detection-retail-0013-4-shave.blob"
      model_face_detection: "@{REL}/models/face_detection_yunet_360x640_sh4.blob"
      model_face_detection_proc: "@{REL}/models/postproc_yunet_top50_th60_360x640_sh4.blob"
      model_depth_diff: "@{REL}/models/diff_images_simplified_openvino_2021.4_4shave.blob"
      model_reid: "@{REL}/models/person-reidentification-retail-0288-4-shave.blob"
video_encoder:
  0: #color
    type: "null"
  1: #depth
    type: "null"
  4: #object-human
    type: "null"